/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function setGlobalKey(key: GlobalKey, value: string) {
    return invoke()<null>("set_global_key", { key,value })
}

export function getGlobalKey(key: GlobalKey) {
    return invoke()<string | null>("get_global_key", { key })
}

export function generateKeyPair() {
    return invoke()<KeyPair>("generate_key_pair")
}

export function discoverNetwork() {
    return invoke()<NetworkInstanceInfo[]>("discover_network")
}

export function getRootDatabaseCredentials() {
    return invoke()<RootDatabaseCredentials>("get_root_database_credentials")
}

export type NetworkInstanceInfo = { center_name: string; version: string; instance_type: InstanceType; local_center_initialized: boolean; ip_addresses: string[] }
export type GlobalKey = "center_id" | "center_name" | "instance_type" | "private_key" | "public_key"
export type InstanceType = "master" | "slave" | "uninitialized"
export type KeyPair = { private_key: string; public_key: string }
export type RootDatabaseCredentials = { username: string; password: string }
