/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function setGlobalKey(key: GlobalKey, value: string) {
    return invoke()<null>("set_global_key", { key,value })
}

export function getGlobalKey(key: GlobalKey) {
    return invoke()<string | null>("get_global_key", { key })
}

export function generateKeyPair() {
    return invoke()<KeyPair>("generate_key_pair")
}

export type GlobalKey = "center_name" | "instance_type" | "private_key"
export type KeyPair = { private_key: string; public_key: string }
