/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function whatsappGetInfo() {
    return invoke()<WhatsAppInfoResponse>("whatsapp_get_info")
}

export function whatsappStartConnection() {
    return invoke()<WhatsAppStartConnectionResponse>("whatsapp_start_connection")
}

export function whatsappSendMessage(body: SendMessageBody) {
    return invoke()<WhatsAppSendMessageResponse>("whatsapp_send_message", { body })
}

export type WhatsAppConnectionStatus = "signed_in" | "signed_out" | "qr_code_generated" | "whatsapp_library_error" | "target_not_on_whatsapp"
export type SendMessageBody = { phone_number: string; message: string }
export type WhatsAppSendMessageResponse = { message_status: WhatsAppMessageStatus; connection_status: WhatsAppConnectionStatus }
export type WhatsAppInfoResponse = { connection_status: WhatsAppConnectionStatus }
export type WhatsAppMessageStatus = "successful" | "failed"
export type WhatsAppStartConnectionResponse = { code: string; connection_status: WhatsAppConnectionStatus }
