[package]
name = "bluetooth-advert-receiver"
version = "0.1.17"
edition = "2021"

[dependencies]
btleplug = "0.11.5"
rand = "0.8.5"
tokio = { version = "1.39.2", features = ["full"] }
uuid = "1.10.0"
