[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.39.1", features = ["rt-multi-thread"] }
serde_json = "1.0"
axum = "0.7.5"
surrealdb = "1.5.4"
config = "0.14.0"
dotenv = "0.15.0"
once_cell = "1.19.0"
