name: Build and Deploy API to Fly.io

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        run: |
          docker build -t registry.fly.io/magmooty-api:latest ./apps
          docker push registry.fly.io/magmooty-api:latest

      - name: Install Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy ./apps --image registry.fly.io/magmooty-api:latest --app magmooty-api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
