name: Build and Deploy API to Fly.io

on:
  push:
    branches:
      - main
    paths:
      - apps/api/**/*
      - apps/telegram-bot/**/*
      - apps/telegram-macros/**/*
      - Dockerfile
      - fly.toml
      - .github/workflows/deploy-api.yml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Adding required env vars for caching sccache
        id: set-vars
        uses: actions/github-script@v7
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            core.setOutput('ACTIONS_CACHE_URL', process.env['ACTIONS_CACHE_URL'])
            core.setOutput('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN'])
            core.setOutput('ACTIONS_RUNTIME_URL', process.env['ACTIONS_RUNTIME_URL'])

      - name: Echo required env vars
        shell: bash
        run: |
          echo "ACTIONS_CACHE_URL: ${{ steps.set-vars.outputs.ACTIONS_CACHE_URL }}"
          echo "ACTIONS_RUNTIME_TOKEN: ${{ steps.set-vars.outputs.ACTIONS_RUNTIME_TOKEN }}"
          echo "ACTIONS_RUNTIME_URL: ${{ steps.set-vars.outputs.ACTIONS_RUNTIME_URL }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: registry.fly.io/magmooty-api:latest
          build-args: |
            SCCACHE_GHA_ENABLED=on
            ACTIONS_CACHE_URL="${{ steps.set-vars.outputs.ACTIONS_CACHE_URL }}"
            ACTIONS_RUNTIME_TOKEN="${{ steps.set-vars.outputs.ACTIONS_RUNTIME_TOKEN }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy . --image registry.fly.io/magmooty-api:latest --app magmooty-api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
