name: Build and Deploy API to Fly.io

on:
  push:
    branches:
      - main
    paths:
      - apps/api/**/*
      - apps/telegram-bot/**/*
      - apps/telegram-macros/**/*
      - Dockerfile
      - fly.toml
      - .github/workflows/deploy-api.yml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        id: cache-docker-layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker Image
        run: |
          docker buildx build --load --build-arg SCCACHE_GHA_ENABLED=on --build-arg ACTIONS_CACHE_URL=$ACTIONS_CACHE_URL --build-arg ACTIONS_RUNTIME_TOKEN=$ACTIONS_RUNTIME_TOKEN -t registry.fly.io/magmooty-api:latest .
        env:
          DOCKER_BUILDKIT: 1

      - name: Install Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy . --image registry.fly.io/magmooty-api:latest --app magmooty-api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
