name: Deploy desktop app

on:
  push:
    branches:
      - main
    paths:
      - apps/desktop/**/*
      - apps/telegram-bot/**/*
      - apps/telegram-macros/**/*
      - .github/workflows/deploy-desktop.yml

jobs:
  bump-version:
    name: Bump app version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Bump version
        uses: tj-actions/cargo-bump@v3
        with:
          release_type: patch
          working-directory: ./apps/desktop

  publish-tauri:
    name: Build and publish desktop app
    needs: bump-version
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: "x64"
            platform: "windows-latest"
            args: ""
          - arch: "x32"
            platform: "windows-latest"
            args: "--target i686-pc-windows-msvc"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./apps/desktop/src-tauri -> target"

      - name: Install frontend dependencies
        run: pnpm install
        working-directory: ./apps/desktop

      - name: vcpkg build ${{ matrix.arch }}
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          pkgs: openssl:${{ matrix.arch }}-windows
          triplet: ${{ matrix.arch }}-windows-release
          token: ${{ github.token }}
          cache-key: vcpkg-cache-${{ matrix.arch }}-windows
          github-binarycache: true

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR: ${{ github.workspace }}/vcpkg/packages/openssl_x64-windows
          X86_PC_WINDOWS_MSVC_OPENSSL_DIR: ${{ github.workspace }}/vcpkg/packages/openssl_x32-windows
        with:
          tagName: app-__VERSION__
          releaseName: "App __VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
