name: Deploy desktop app

on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./apps/desktop/src-tauri -> target"

      - name: Install frontend dependencies
        run: pnpm install
        working-directory: ./apps/desktop

      - name: vcpkg build
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          pkgs: openssl:x64-windows
          triplet: x64-windows-release
          token: ${{ github.token }}
          github-binarycache: true

      # - uses: tauri-apps/tauri-action@v0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR: ${{ github.workspace }}/packages/openssl_x64-windows
      #   with:
      #     tagName: app-v1.0.0
      #     releaseName: "App v1.0.0"
      #     releaseBody: "See the assets to download this version and install."
      #     releaseDraft: true
      #     prerelease: false
      #     args: ${{ matrix.args }}
      #     working-directory: ./apps/desktop
