name: Run Tests on Desktop App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-desktop:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21'

    - name: Cache pnpm store
      id: pnpm-cache
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('apps/desktop/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Install dependencies
      run: pnpm install
      working-directory: apps/desktop
      if: steps.pnpm-cache.outputs.cache-hit != 'true'

    - name: Start SurrealDB
      uses: jvllmr/surrealdb-action@2.0.0
      with:
        surrealdb-version: v1.5.4
        surrealdb-port: 7002
        surrealdb-user: root
        surrealdb-password: root

    - name: Run tests for Desktop App
      run: SKIP_SURREAL=1 pnpm test
      working-directory: apps/desktop