name: Run Tests on Central API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - stage

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust: [stable]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy

      - uses: Swatinem/rust-cache@v2

      - name: Build the project
        run: cargo build -p api --verbose

      - name: Run tests
        run: cargo test -p api --verbose