name: Upload files to Fly.io

on:
  push:
    branches:
      - stage
    paths:
      - .github/workflows/upload-to-s3.yml

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest

    steps:
      - run: |
          wget https://github.com/magmooty/monorepo/releases/download/app-0.0.25/Magmooty_0.0.25_x64-setup.exe
          mv Magmooty_0.0.25_x64-setup.exe artifacts/

      - uses: shallwefootball/s3-upload-action@master
        with:
          endpoint: https://fly.storage.tigris.dev
          aws_key_id: ${{ secrets.FLY_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.FLY_AWS_SECRET_ACCESS_KEY }}
          aws_bucket: magmooty-desktop-releases
          source_dir: "artifacts"
          destination_dir: "v0.0.1"
